name = "fibercandy"
account_id = "f1e3ef2dd5e12ee616725b88d7c9d629"

main = "./.svelte-kit/cloudflare/_worker.js"
site.bucket = "./.svelte-kit/cloudflare/"

build.command = "npm run build"

compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-11-30"

workers_dev = true
